# Generated by Django 4.0.2 on 2022-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510, verbose_name='コンテンツ名')),
                ('url', models.URLField(max_length=510, verbose_name='コンテンツURL')),
                ('thumbnail', models.URLField(max_length=510, null=True, verbose_name='サムネイルURL')),
                ('content_type', models.CharField(choices=[('nikodo', 'ニコニコ動画'), ('youtube', 'Youtube'), ('spotify', 'Spotify')], max_length=50, verbose_name='コンテンツのタイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.ManyToManyField(related_name='contents', to='playlist.Content', verbose_name='コンテンツ')),
            ],
        ),
    ]
