# Generated by Django 4.0.2 on 2022-02-19 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510, unique=True, verbose_name='プレイリスト名')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'プレイリスト',
                'verbose_name_plural': 'プレイリスト一覧',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='並び順')),
                ('name', models.CharField(max_length=255, verbose_name='コンテンツ名')),
                ('url', models.URLField(max_length=510, verbose_name='コンテンツURL')),
                ('thumbnail', models.URLField(max_length=510, null=True, verbose_name='サムネイルURL')),
                ('content_type', models.CharField(choices=[('nikodo', 'ニコニコ動画'), ('youtube', 'Youtube'), ('spotify', 'Spotify')], max_length=50, verbose_name='コンテンツのタイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='playlist.playlist', verbose_name='プレイリスト')),
            ],
            options={
                'verbose_name': '保存コンテンツ',
                'verbose_name_plural': '保存コンテンツ一覧',
                'ordering': ['order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
    ]
