# Generated by Django 4.0.2 on 2022-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '保存コンテンツ', 'verbose_name_plural': '保存コンテンツ一覧'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'プレイリスト', 'verbose_name_plural': 'プレイリスト一覧'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='hoge', max_length=510, unique=True, verbose_name='プレイリスト名'),
            preserve_default=False,
        ),
    ]
